# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graph-Writer-TGXML
version:      0.01
version_from: 
installdirs:  site
requires:
    Graph:                         0
    XML::Writer:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
